services:
  postgres:
    image: "postgres:17"
    container_name: tasks-manager-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks-manager
